general {
  hide_cursor = false
  grace = 1
}

background {
  # Hiển thị hình nền động hoặc ảnh chụp màn hình
  path = /home/ngochithuan/.config/hypr/wallpapers/wallpaper1.png
  blur_passes = 2
}

input-field {
  size = 250, 50
  outline_thickness = 2
  dots_size = 0.1
  dots_spacing = 0.15
  hide_input = false
  placeholder_text = <i>Password...</i>
  position = 0, 300
  halign = center
  valign = bottom
}

# Hiển thị thời gian ở giữa màn hình
label {
  monitor = 0
  text = cmd [update:1000] echo "<b><big>$(date +\"%H:%M:%S\")</big></b>"
  font_size = 90
  position = 0, 0
  halign = center
  valign = center
}

